version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: clean-jsdoc-theme
    versions:
    - 3.2.4
